# Generated by Django 5.0.4 on 2024-04-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('isLost', models.BooleanField(default=True)),
                ('specie', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='animal_photos/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
