# Generated by Django 5.0.4 on 2024-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
